name: Deploy e Verify

on:
  push:
    branches:
      - feature/gamificacao

env:
  NETWORK: sepolia

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: List dependencies
        run: npm list @openzeppelin/hardhat-upgrades

      - name: Reinstall upgrades
        run: npm install --save-dev @openzeppelin/hardhat-upgrades

      - name: Deploy contracts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }} # Chave privada como segredo
          INFURA_SEPOLIA_URL: ${{ secrets.INFURA_SEPOLIA_URL }} # URL RPC da Sepolia como segredo
          DEPLOYER_ADDRESS: ${{ secrets.DEPLOYER_ADDRESS }} # Endereço da carteira do deployer
          NAME_TOKEN: ${{ vars.NAME_TOKEN }} # Nome do token
          SYMBOL: ${{ vars.SYMBOL }} # Símbolo do token
          PAYMENT_TOKEN_ADDRESS: ${{ vars.PAYMENT_TOKEN_ADDRESS }} # Endereço do pagamento do usdc
          TREASURY_ADDRESS: ${{ vars.TREASURY_ADDRESS }} # Endereço do tesouro
          MARKETPLACE_CONTRACT_ADDRESS: ${{ vars.MARKETPLACE_CONTRACT_ADDRESS }} 
          USDC_TOKEN_ADDRESS: ${{ vars.USDC_TOKEN_ADDRESS }} 
          LOGIC_CONTRACT_ADDRESS: ${{ vars.LOGIC_CONTRACT_ADDRESS }} 
          PROXY_CONTRACT_ADDRESS: ${{ vars.PROXY_CONTRACT_ADDRESS }}
        run: npx hardhat run scripts/deploy.js --network $NETWORK