name: Deploy e Verify

on:
  push:
    branches:
      - main

env:
  NETWORK: sepolia

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: List dependencies
        run: npm list @openzeppelin/hardhat-upgrades

      - name: Reinstall upgrades
        run: npm install --save-dev @openzeppelin/hardhat-upgrades

      - name: Deploy contracts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }} # Chave privada como segredo
          INFURA_SEPOLIA_URL: ${{ secrets.INFURA_SEPOLIA_URL }} # URL RPC da Sepolia como segredo
          DEPLOYER_ADDRESS: ${{ secrets.DEPLOYER_ADDRESS }} # Endereço da carteira do deployer
          NAME_TOKEN: ${{ vars.NAME_TOKEN }} # Nome do token
          SYMBOL: ${{ vars.SYMBOL }} # Símbolo do token
          LOGIC_CONTRACT_ADDRESS: ${{ vars.LOGIC_CONTRACT_ADDRESS }} 
          PROXY_CONTRACT_ADDRESS: ${{ vars.PROXY_CONTRACT_ADDRESS }}
        run: npx hardhat run scripts/deploy.js --network $NETWORK

  verify:
    name: Verify Contracts
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Verify Contracts
        env:
          LOGIC_CONTRACT_ADDRESS: ${{ vars.LOGIC_CONTRACT_ADDRESS }} 
          PROXY_CONTRACT_ADDRESS: ${{ vars.PROXY_CONTRACT_ADDRESS }}
          ADMIN_ADDRESS: ${{ secrets.DEPLOYER_ADDRESS }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          INFURA_SEPOLIA_URL: ${{ secrets.INFURA_SEPOLIA_URL }}
        run: node scripts/verify.js